before_script:
  #- mkdir -p build


variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - test
  #- pages
  #- deploy

build_job:
  stage: build
  script:
    - echo $CMAKE_MODULE
    - echo $CMAKE_ENABLE_CPP20
    - module purge
    - module load $CMAKE_MODULE $CXX_MODULE_COMPILER
    - mkdir -p build && cd build
    - cmake ../ -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_CXX_FLAGS="-Wall -fmax-errors=4" -DCMAKE_CXX_FLAGS_RELEASE="-O3 -march=native -DNDEBUG" -DSTD_E_ENABLE_COVERAGE=OFF -DSTD_E_BUILD_DOCUMENTATION=OFF -DSTD_E_ENABLE_MPI=$CMAKE_ENABLE_MPI -DSTD_E_ENABLE_CPP20=$CMAKE_ENABLE_CPP20
    - make -j4
    - ./std_e_unit_tests -r=junit > report.xml
    - pwd
  artifacts:
    paths:
      - build/
    expire_in: 1 day
    reports:
      junit: build/report.xml
  parallel:
    matrix:
        - CXX_MODULE_COMPILER: ["gcc/8.3"]
          CMAKE_BUILD_TYPE: ["Debug"]
          CMAKE_MODULE: ["cmake/3.19-gnu"]
          CMAKE_ENABLE_MPI: ["OFF"]
          CMAKE_ENABLE_CPP20: ["OFF"]

test_job:
  stage: test
  dependencies:
    - build_job
  script:
    - echo "lala"
    - pwd
    - ls -lArth
    - ls build/
    - cd build && ./std_e_unit_tests
    - echo "tata"
