before_script:
 - apt-get update --yes
 - apt-get install --yes cmake
 
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages: # Ici on déclare toutes nos étapes
  - build
  # - test
  # - deploy

job:build:
  stage: build # On déclare que ce `job` fait partie de l'étape build
  script:
    - echo "HELLLO"
    - hostname
    - echo "HELLLO2"
    - echo "HELLLO2"
    - whoami
    - ls -lrt /home/bmaugars
    - apt-get update --yes
    - apt-get install --yes gcc
    - pwd
    - module av
    - echo $PWD
    - ls -lrt
    - cd ..
    - ls -lrt
    - cd build
    - module load gcc/5.2 cmake/3.12.3 impi/17 python/2.7.8
    - cmake ../pr
    - make
    - make test

job:test:
  stage: test # On déclare que ce `job` fait partie de l'étape build
  script:
    - ls -lrt
    - cd ../build
    - echo $PWD
    - module load gcc/5.2 cmake/3.12.3 impi/17 python/2.7.8
    - make test