name: std_e C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

post:
  git submodule sync --recursive
  git submodule update --init --recursive

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Test Debug x64
      run: |
        cmake -E remove_directory build
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug 
        cmake --build build
        cd build
        ctest
